---
name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install lint tools
        run: pip install ansible-lint yamllint

      - name: Run yamllint
        run: yamllint -c .config/yamllint.yml .

      - name: Run ansible-lint
        run: ansible-lint  # сам найдёт .config/ansible-lint.yml

  molecule:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install ansible molecule "molecule-plugins[docker]" docker

      - name: Run molecule test
        run: molecule test
